repos:
  - repo: https://github.com/stelligent/cfn_nag
    rev: v0.8.9
    hooks:
      - id: cfn-nag
        files: cloudformation/.*\.(json|yml|yaml)$
      - id: cfn-nag
        files: app-sam/.*\.(yml|yaml)$
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.58.3
    hooks:
      - id: cfn-python-lint
        args: [--update-specs]
        files: cloudformation/.*\.(json|yml|yaml)$
      - id: cfn-python-lint
        files: app-sam/.*\.(json|yml|yaml)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: no-commit-to-branch
        args: [--branch=master, --branch=main]
      - id: trailing-whitespace
