version: '3.7'

services:

  devops:
    # image: python:3.8  
    # image: amazon/aws-lambda-python:3.8.2021.09.13.11
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}  
    container_name: devops
    build:
      context: ./
      dockerfile: Dockerfile
      args:
          HELM_VERSION: ${HELM_VERSION}
          KUBE_VERSION: ${KUBE_VERSION}
          ALPINE_VERSION: ${ALPINE_VERSION}
          TERRAFORM_VERSION: ${TERRAFORM_VERSION}
          TARGETOS: ${TARGETOS}
          TARGETARCH: ${TARGETARCH}
          YQ_VERSION: ${YQ_VERSION}
          TEMPLER_VERSION: ${TEMPLER_VERSION}
          JINJA_VERSION: ${JINJA_VERSION}            
    tty: true
    platform: linux/x86_64
    volumes:
      - "~/.aws/credentials:/root/.aws/credentials:ro"
      - "~/.ssh:/root/.ssh:ro"
      - ".:/app"
      # - "${SSH_AUTH_SOCK}:/ssh-agent"
      - /var/run/docker.sock:/var/run/docker.sock      
    entrypoint: /usr/local/bin/docker-entrypoint
    command: ["bash"]
    # command: ["/bin/sh"]
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_DEFAULT_PROFILE
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN    
    env_file:
      - .env