version: '3.7'

networks:
  stack:
    driver: bridge
    name: devops-stack

services:

  devops:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: devops
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${PWD}:/app
      - ${HOME}/.ssh/id_rsa.pub:/root/id_rsa.pub
      - ${HOME}/.ssh/id_rsa:/root/id_rsa
    entrypoint: /usr/local/bin/docker-entrypoint
    command: ["bash"]
    env_file:
      - .env
    networks:
      - stack
