version: '3.7'

networks:
  dev-stack:
    driver: bridge
    name: dev-stack

services:

  terraform:
    image: ${DOCKER_REGISTORY}/${DOCKER_REPOSITORY}/terraform:latest
    container_name: ${DOCKER_REGISTORY}-terraform
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${PWD}:/app
      - ${HOME}/.ssh/id_rsa.pub:/root/id_rsa.pub
      - ${HOME}/.ssh/id_rsa:/root/id_rsa
    command: ["bash"]
    env_file:
      - .env
    networks:
      - dev-stack
