Parameters:
  EnvironmentName:
    Description: Provide the environment name
    Type: String
    Default: base
  EnvironmentProfile:
    Description: Select the environment profile
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
  EnvironmenOwner:
    Description: provide the environment owner
    Type: String
    Default: sam
  StackName:
    Description: provide the stack name
    Type: String
    Default: sam